Avoid a fatal error when activating GiveWP for a new site
If GiveWP is activated on a new site, there is a fatal error: 
Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/wordpress/wp-content/plugins/give/src/PaymentGateways/Gateways/PayPalStandard/Migrations/SetPayPalStandardGatewayId.php:30 Stack trace: #0 

For a new site, no gateway is defined, and $gateways is null.